spring.application.name=pharmacy-management
#spring.mongodb.uri=mongodb://localhost:27017/pharmacy_db

spring.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}
#server.port=8080

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG